"use client";
import React from "react";
import "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import "tailwindcss/tailwind.css";
import theme from "@/app/theme";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import { metadata } from "@/app/metaData";

metadata.title = "Create Next App";
metadata.description = "Generated by create next app";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <NavBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
