"use client";
import React from "react";
import "@/app/globals.css";
import NavBar from "@/components/NavBar";
import "tailwindcss/tailwind.css";
import theme from "@/app/theme";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import { metadata } from "@/app/metaData";
import Footer from "@/components/Footer";
import ProductList from "@/components/ProductList";
import HomePage from "@/components/Homepage";


metadata.title = "Create Next App";
metadata.description = "Generated by create next app";

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className="flex flex-col min-h-screen" 
      >
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <NavBar />
          <main className="flex-grow">{children}</main> 
          <Footer /> 
        </ThemeProvider>
      </body>
    </html>
  );
}
