import "@/app/globals.css";
import NavBar from "@/components/NavBar";
import "tailwindcss/tailwind.css";
import { metadata } from "@/app/metaData";
import Footer from "@/components/Footer";
import ThemeClient from "@/components/ThemeClient";



metadata.title = "Create Next App";
metadata.description = "Generated by create next app";

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className="flex flex-col min-h-screen">
        <ThemeClient>
          <NavBar />
          <main className="flex-grow">{children}</main>
          <Footer />
        </ThemeClient>
      </body>
    </html>
  );
}
